global:
  slack_api_url: https://YOUR-SLACK-HOOK

route:
  receiver: 'slack'

receivers:
  - name: 'slack'
    slack_configs:
      - send_resolved: true
        title: '{{ template "custom_title" . }}'
        text: '{{ template "custom_slack_message" . }}'
        username: alertmanager
        channel: alerts

templates:
  - /etc/alertmanager/notifications.tmpl